services:
  apache:
    build: ./apache
    image: multi-apache
    restart: unless-stopped
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./sites:/var/www
      - ./apache/apache.conf:/etc/apache2/apache2.conf:ro
      - ./apache/ports.conf:/etc/apache2/ports.conf:ro
      - ./vhosts/sites-available:/etc/apache2/sites-available:rw
      - ./vhosts/sites-enabled:/etc/apache2/sites-enabled:rw
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - web

  php81:
    build: ./php/8.1  # This points to the location of your new Dockerfile
    container_name: php81
    restart: unless-stopped
    volumes:
      - ./php/8.1/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/8.1/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./sites:/var/www

    networks:
      - web

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Frankie2Hollis
    volumes:
      - ./mysql/data:/var/lib/mysql      # Persist MySQL data
      - ./mysql/init:/docker-entrypoint-initdb.d  # Custom init scripts
    ports:
      - "3306:3306"
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/run-certbot.sh:/usr/local/bin/run-certbot.sh:ro
      - ./certbot/www:/var/www/certbot
    entrypoint: ["/usr/local/bin/run-certbot.sh"]

networks:
  web:
    driver: bridge

volumes:
  letsencrypt:
