version = 5.3.0
archive_dir = /etc/letsencrypt/archive/cloud.dm4ab.de
cert = /etc/letsencrypt/live/cloud.dm4ab.de/cert.pem
privkey = /etc/letsencrypt/live/cloud.dm4ab.de/privkey.pem
chain = /etc/letsencrypt/live/cloud.dm4ab.de/chain.pem
fullchain = /etc/letsencrypt/live/cloud.dm4ab.de/fullchain.pem
[renewalparams]
account = b9f57d634ca0f7cbfe378d5b7cee96b6
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
cloud.dm4ab.de = /var/www/certbot
