version = 5.3.0
archive_dir = /etc/letsencrypt/archive/tueftel-treff.de
cert = /etc/letsencrypt/live/tueftel-treff.de/cert.pem
privkey = /etc/letsencrypt/live/tueftel-treff.de/privkey.pem
chain = /etc/letsencrypt/live/tueftel-treff.de/chain.pem
fullchain = /etc/letsencrypt/live/tueftel-treff.de/fullchain.pem
[renewalparams]
account = b9f57d634ca0f7cbfe378d5b7cee96b6
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
tueftel-treff.de = /var/www/certbot
www.tueftel-treff.de = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-02-23T04:42:09
