
## watch out for multiple uses of domain and ssl keys, 
## port 80, 443

<VirtualHost *:80>
    ServerName amateurfunk-ulm.de 
    DocumentRoot /var/www/amateurfunk-ulm

    ## need this for ACME challenfge so the challenge knows where to write to, always same dir, for all vhosts
    Alias /.well-known/acme-challenge/ /var/www/certbot/.well-known/acme-challenge/
    <Directory "/var/www/certbot/.well-known/acme-challenge">
        Options None
        AllowOverride None
        Require all granted
    </Directory>
    # more for ACME
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]    
    ## end ACME

    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://php81:9000/"
    </FilesMatch>

    <Directory /var/www/amateurfunk-ulm>
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/amateurfunk-ulm-error.log
    CustomLog ${APACHE_LOG_DIR}/amateurfunk-ulm-access.log combined
</VirtualHost>

<VirtualHost *:443>
    ServerName amateurfunk-ulm.de
    DocumentRoot /var/www/amateurfunk-ulm

    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://php81:9000/"
    </FilesMatch>

    <Directory /var/www/amateurfunk-ulm>
        AllowOverride All
        Require all granted
    </Directory>

    # TLS
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/amateurfunk-ulm.de/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/amateurfunk-ulm.de/privkey.pem

    ErrorLog ${APACHE_LOG_DIR}/amateurfunk-ulm-ssl-error.log
    CustomLog ${APACHE_LOG_DIR}/amateurfunk-ulm-ssl-access.log combined
</VirtualHost>
